/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ResetPasswordImport } from './routes/reset-password'
import { Route as RecoverPasswordImport } from './routes/recover-password'
import { Route as LoginImport } from './routes/login'
import { Route as LandingImport } from './routes/landing'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as BookingUsernameImport } from './routes/booking.$username'
import { Route as LayoutSettingsImport } from './routes/_layout/settings'
import { Route as LayoutServicesImport } from './routes/_layout/services'
import { Route as LayoutClientsImport } from './routes/_layout/clients'
import { Route as LayoutCalendarImport } from './routes/_layout/calendar'
import { Route as LayoutAdminImport } from './routes/_layout/admin'
import { Route as BookingUsernameIndexImport } from './routes/booking.$username/index'
import { Route as BookingUsernameServicesImport } from './routes/booking.$username/services'
import { Route as BookingUsernamePortfolioImport } from './routes/booking.$username/portfolio'
import { Route as BookingUsernameAboutImport } from './routes/booking.$username/about'

// Create/Update Routes

const ResetPasswordRoute = ResetPasswordImport.update({
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const RecoverPasswordRoute = RecoverPasswordImport.update({
  path: '/recover-password',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LandingRoute = LandingImport.update({
  path: '/landing',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const BookingUsernameRoute = BookingUsernameImport.update({
  path: '/booking/$username',
  getParentRoute: () => rootRoute,
} as any)

const LayoutSettingsRoute = LayoutSettingsImport.update({
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutServicesRoute = LayoutServicesImport.update({
  path: '/services',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutClientsRoute = LayoutClientsImport.update({
  path: '/clients',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutCalendarRoute = LayoutCalendarImport.update({
  path: '/calendar',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAdminRoute = LayoutAdminImport.update({
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

const BookingUsernameIndexRoute = BookingUsernameIndexImport.update({
  path: '/',
  getParentRoute: () => BookingUsernameRoute,
} as any)

const BookingUsernameServicesRoute = BookingUsernameServicesImport.update({
  path: '/services',
  getParentRoute: () => BookingUsernameRoute,
} as any)

const BookingUsernamePortfolioRoute = BookingUsernamePortfolioImport.update({
  path: '/portfolio',
  getParentRoute: () => BookingUsernameRoute,
} as any)

const BookingUsernameAboutRoute = BookingUsernameAboutImport.update({
  path: '/about',
  getParentRoute: () => BookingUsernameRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/landing': {
      preLoaderRoute: typeof LandingImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/recover-password': {
      preLoaderRoute: typeof RecoverPasswordImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      preLoaderRoute: typeof ResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/_layout/admin': {
      preLoaderRoute: typeof LayoutAdminImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/calendar': {
      preLoaderRoute: typeof LayoutCalendarImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/clients': {
      preLoaderRoute: typeof LayoutClientsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/services': {
      preLoaderRoute: typeof LayoutServicesImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/settings': {
      preLoaderRoute: typeof LayoutSettingsImport
      parentRoute: typeof LayoutImport
    }
    '/booking/$username': {
      preLoaderRoute: typeof BookingUsernameImport
      parentRoute: typeof rootRoute
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/booking/$username/about': {
      preLoaderRoute: typeof BookingUsernameAboutImport
      parentRoute: typeof BookingUsernameImport
    }
    '/booking/$username/portfolio': {
      preLoaderRoute: typeof BookingUsernamePortfolioImport
      parentRoute: typeof BookingUsernameImport
    }
    '/booking/$username/services': {
      preLoaderRoute: typeof BookingUsernameServicesImport
      parentRoute: typeof BookingUsernameImport
    }
    '/booking/$username/': {
      preLoaderRoute: typeof BookingUsernameIndexImport
      parentRoute: typeof BookingUsernameImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRoute.addChildren([
    LayoutAdminRoute,
    LayoutCalendarRoute,
    LayoutClientsRoute,
    LayoutServicesRoute,
    LayoutSettingsRoute,
    LayoutIndexRoute,
  ]),
  LandingRoute,
  LoginRoute,
  RecoverPasswordRoute,
  ResetPasswordRoute,
  BookingUsernameRoute.addChildren([
    BookingUsernameAboutRoute,
    BookingUsernamePortfolioRoute,
    BookingUsernameServicesRoute,
    BookingUsernameIndexRoute,
  ]),
])

/* prettier-ignore-end */
