/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ResetPasswordImport } from './routes/reset-password'
import { Route as RecoverPasswordImport } from './routes/recover-password'
import { Route as LoginImport } from './routes/login'
import { Route as LandingImport } from './routes/landing'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as BookingShopNameImport } from './routes/booking.$shopName'
import { Route as LayoutSettingsImport } from './routes/_layout/settings'
import { Route as LayoutServicesImport } from './routes/_layout/services'
import { Route as LayoutClientsImport } from './routes/_layout/clients'
import { Route as LayoutCalendarImport } from './routes/_layout/calendar'
import { Route as LayoutAdminImport } from './routes/_layout/admin'
import { Route as BookingShopNameIndexImport } from './routes/booking.$shopName/index'
import { Route as BookingShopNameServicesImport } from './routes/booking.$shopName/services'
import { Route as BookingShopNamePortfolioImport } from './routes/booking.$shopName/portfolio'
import { Route as BookingShopNameAboutImport } from './routes/booking.$shopName/about'

// Create/Update Routes

const ResetPasswordRoute = ResetPasswordImport.update({
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const RecoverPasswordRoute = RecoverPasswordImport.update({
  path: '/recover-password',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LandingRoute = LandingImport.update({
  path: '/landing',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const BookingShopNameRoute = BookingShopNameImport.update({
  path: '/booking/$shopName',
  getParentRoute: () => rootRoute,
} as any)

const LayoutSettingsRoute = LayoutSettingsImport.update({
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutServicesRoute = LayoutServicesImport.update({
  path: '/services',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutClientsRoute = LayoutClientsImport.update({
  path: '/clients',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutCalendarRoute = LayoutCalendarImport.update({
  path: '/calendar',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAdminRoute = LayoutAdminImport.update({
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

const BookingShopNameIndexRoute = BookingShopNameIndexImport.update({
  path: '/',
  getParentRoute: () => BookingShopNameRoute,
} as any)

const BookingShopNameServicesRoute = BookingShopNameServicesImport.update({
  path: '/services',
  getParentRoute: () => BookingShopNameRoute,
} as any)

const BookingShopNamePortfolioRoute = BookingShopNamePortfolioImport.update({
  path: '/portfolio',
  getParentRoute: () => BookingShopNameRoute,
} as any)

const BookingShopNameAboutRoute = BookingShopNameAboutImport.update({
  path: '/about',
  getParentRoute: () => BookingShopNameRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/landing': {
      preLoaderRoute: typeof LandingImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/recover-password': {
      preLoaderRoute: typeof RecoverPasswordImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      preLoaderRoute: typeof ResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/_layout/admin': {
      preLoaderRoute: typeof LayoutAdminImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/calendar': {
      preLoaderRoute: typeof LayoutCalendarImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/clients': {
      preLoaderRoute: typeof LayoutClientsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/services': {
      preLoaderRoute: typeof LayoutServicesImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/settings': {
      preLoaderRoute: typeof LayoutSettingsImport
      parentRoute: typeof LayoutImport
    }
    '/booking/$shopName': {
      preLoaderRoute: typeof BookingShopNameImport
      parentRoute: typeof rootRoute
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/booking/$shopName/about': {
      preLoaderRoute: typeof BookingShopNameAboutImport
      parentRoute: typeof BookingShopNameImport
    }
    '/booking/$shopName/portfolio': {
      preLoaderRoute: typeof BookingShopNamePortfolioImport
      parentRoute: typeof BookingShopNameImport
    }
    '/booking/$shopName/services': {
      preLoaderRoute: typeof BookingShopNameServicesImport
      parentRoute: typeof BookingShopNameImport
    }
    '/booking/$shopName/': {
      preLoaderRoute: typeof BookingShopNameIndexImport
      parentRoute: typeof BookingShopNameImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRoute.addChildren([
    LayoutAdminRoute,
    LayoutCalendarRoute,
    LayoutClientsRoute,
    LayoutServicesRoute,
    LayoutSettingsRoute,
    LayoutIndexRoute,
  ]),
  LandingRoute,
  LoginRoute,
  RecoverPasswordRoute,
  ResetPasswordRoute,
  BookingShopNameRoute.addChildren([
    BookingShopNameAboutRoute,
    BookingShopNamePortfolioRoute,
    BookingShopNameServicesRoute,
    BookingShopNameIndexRoute,
  ]),
])

/* prettier-ignore-end */
